dataset:
  train:
    target: autoencoder.dataset.tumor.BraTS2021Dataset
    params:
      root: /path/to/train/data
      modalites: ["t1", "t1ce", "t2", "flair"]
      slice_range: [27, 127]
  val:
    target: autoencoder.dataset.tumor.BraTS2021Dataset
    params:
      root: /path/to/val/data
      modalites: ["t1", "t1ce", "t2", "flair"]
      masked: [2]
      slice_range: [27, 127]
  test:
    target: autoencoder.dataset.tumor.BraTS2021Dataset
    params:
      root: /path/to/test/data
      modalites: ["t1", "t1ce", "t2", "flair"]
      masked: [2, 4]
      slice_range: [27, 127]

model:
  target: autoencoder.kernel.model.VQVAE
  params:
    backbone_config:
      double_z: False
      z_channels: 64
      resolution: 224
      in_channels: 4
      out_ch: 4
      ch: 128
      ch_mult: [1, 1, 2, 2, 4] # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    quantizer_config:
      n_e: 4096
      e_dim: 64

    loss_config:
      target: autoencoder.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 4
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0
    # ckpt_path: ...
    # ignore_keys: ...
    # learning_rate: 1e-4

trainer:
  max_epochs: 100
  callbacks:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: /path/to/checkpoints/ # Update this path to your desired checkpoint directory
      filename: best-checkpoint-epoch{epoch:02d}-aeloss{train/aeloss:.2f}
      monitor: train/aeloss
      mode: min
      save_top_k: 5
      auto_insert_metric_name: False
  logger:
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: /path/to/logs/ # Update this path to your desired log directory
      name: vqvae
